package undisk

// Code generated by scripts/generate_types.py from tools.json. DO NOT EDIT.

// Tool name constants for all Undisk MCP tools.
const (
	ToolAppendLog = "append_log"
	ToolAuditTrail = "audit_trail"
	ToolCreateFile = "create_file"
	ToolDeleteFile = "delete_file"
	ToolDiscoverToolsAndCapabilities = "discover_tools_and_capabilities"
	ToolFederation = "federation"
	ToolGetDiff = "get_diff"
	ToolListChanges = "list_changes"
	ToolListFiles = "list_files"
	ToolListVersions = "list_versions"
	ToolListWorkspaces = "list_workspaces"
	ToolMoveFile = "move_file"
	ToolPolicy = "policy"
	ToolReadFile = "read_file"
	ToolRestoreVersion = "restore_version"
	ToolRunInSandbox = "run_in_sandbox"
	ToolSearchFiles = "search_files"
	ToolShareWithPublic = "share_with_public"
	ToolUploadSession = "upload_session"
	ToolVaultSecret = "vault_secret"
	ToolWebhook = "webhook"
	ToolWorkspaceCheckpoint = "workspace_checkpoint"
	ToolWorkspaceCollaborate = "workspace_collaborate"
	ToolWriteFile = "write_file"
)

// AllToolNames contains all available Undisk MCP tool names.
var AllToolNames = []string{
	"append_log",
	"audit_trail",
	"create_file",
	"delete_file",
	"discover_tools_and_capabilities",
	"federation",
	"get_diff",
	"list_changes",
	"list_files",
	"list_versions",
	"list_workspaces",
	"move_file",
	"policy",
	"read_file",
	"restore_version",
	"run_in_sandbox",
	"search_files",
	"share_with_public",
	"upload_session",
	"vault_secret",
	"webhook",
	"workspace_checkpoint",
	"workspace_collaborate",
	"write_file",
}

// AppendLogInput contains the input parameters for the append_log tool.
// Append log entries to a file without overwriting. Ideal for shared logs across agents, sessions, and
type AppendLogInput struct {
	Content string `json:"content"`
	Path string `json:"path"`
}

// AuditTrailInput contains the input parameters for the audit_trail tool.
// Query the workspace's tamper-evident audit trail. Use 'list' to browse entries with filters, 'export
type AuditTrailInput struct {
	Action string `json:"action"`
	AgentID *string `json:"agentId,omitempty"`
	EndTime *string `json:"endTime,omitempty"`
	FilePath *string `json:"filePath,omitempty"`
	Format *string `json:"format,omitempty"`
	FromSeq *float64 `json:"fromSeq,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	OperationType *string `json:"operationType,omitempty"`
	StartTime *string `json:"startTime,omitempty"`
	ToSeq *float64 `json:"toSeq,omitempty"`
	ToolName *string `json:"toolName,omitempty"`
}

// CreateFileInput contains the input parameters for the create_file tool.
// Create a new file (fails if path already exists). Use write_file for upsert behavior.
type CreateFileInput struct {
	Content string `json:"content"`
	Encoding *string `json:"encoding,omitempty"`
	Path string `json:"path"`
}

// DeleteFileInput contains the input parameters for the delete_file tool.
// Soft-delete a file or directory. Set recursive: true to delete all files under a path. Each file is 
type DeleteFileInput struct {
	Path string `json:"path"`
	Recursive *bool `json:"recursive,omitempty"`
}

// DiscoverToolsAndCapabilitiesInput contains the input parameters for the discover_tools_and_capabilities tool.
// Call after tools/list to learn available tools, server capabilities, provider-specific feature flags
type DiscoverToolsAndCapabilitiesInput struct {
}

// FederationInput contains the input parameters for the federation tool.
// Cross-workspace file federation: create read-only links to files in other workspaces you own. Read f
type FederationInput struct {
	Action string `json:"action"`
	Alias *string `json:"alias,omitempty"`
	LinkID *string `json:"link_id,omitempty"`
	TargetPath *string `json:"target_path,omitempty"`
	TargetWorkspace *string `json:"target_workspace,omitempty"`
}

// GetDiffInput contains the input parameters for the get_diff tool.
// Structured diff between two versions: changes with type (added/removed/modified), line ranges, and b
type GetDiffInput struct {
	FromVersion string `json:"from_version"`
	Path string `json:"path"`
	ToVersion string `json:"to_version"`
}

// ListChangesInput contains the input parameters for the list_changes tool.
// Query all changes across the workspace by agent and/or time range. At least one filter required. Ret
type ListChangesInput struct {
	AgentID *string `json:"agentId,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	Since *string `json:"since,omitempty"`
}

// ListFilesInput contains the input parameters for the list_files tool.
// List files in a directory. Supports recursive listing. Returns up to 1,000 entries per call.
type ListFilesInput struct {
	Path *string `json:"path,omitempty"`
	Recursive *bool `json:"recursive,omitempty"`
}

// ListVersionsInput contains the input parameters for the list_versions tool.
// Show version history for a file: timestamp, agent, content hash, size.
type ListVersionsInput struct {
	AgentID *string `json:"agentId,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	Offset *float64 `json:"offset,omitempty"`
	Path string `json:"path"`
	Since *string `json:"since,omitempty"`
}

// ListWorkspacesInput contains the input parameters for the list_workspaces tool.
// List all workspaces accessible to the current API key. Returns provider, org membership, current wor
type ListWorkspacesInput struct {
}

// MoveFileInput contains the input parameters for the move_file tool.
// Move or rename a file or directory. Set recursive: true to move all files under a path. Full audit t
type MoveFileInput struct {
	FromPath string `json:"from_path"`
	Recursive *bool `json:"recursive,omitempty"`
	ToPath string `json:"to_path"`
}

// PolicyInput contains the input parameters for the policy tool.
// Get, validate, or set workspace access rules and limits. Use action 'read' to fetch current policy, 
type PolicyInput struct {
	Action string `json:"action"`
	Add *map[string]any `json:"add,omitempty"`
	ExtensionRules *[]map[string]any `json:"extensionRules,omitempty"`
	Mode *string `json:"mode,omitempty"`
	PathACLs *[]map[string]any `json:"pathAcls,omitempty"`
	RateLimits *[]map[string]any `json:"rateLimits,omitempty"`
	Remove *map[string]any `json:"remove,omitempty"`
	SecretScanning *map[string]any `json:"secretScanning,omitempty"`
	SizeLimits *[]map[string]any `json:"sizeLimits,omitempty"`
}

// ReadFileInput contains the input parameters for the read_file tool.
// Read file contents by path. Returns UTF-8 text or base64 for binary with a mimeType hint, plus metad
type ReadFileInput struct {
	LineEnd *float64 `json:"line_end,omitempty"`
	LineStart *float64 `json:"line_start,omitempty"`
	Path string `json:"path"`
	VersionID *string `json:"version_id,omitempty"`
}

// RestoreVersionInput contains the input parameters for the restore_version tool.
// Restore a file to any prior version. Creates a new version with restored content.
type RestoreVersionInput struct {
	Path string `json:"path"`
	VersionID string `json:"version_id"`
}

// RunInSandboxInput contains the input parameters for the run_in_sandbox tool.
// Execute code in a secure, ephemeral E2B cloud sandbox and return stdout, stderr, and exit code. Supp
type RunInSandboxInput struct {
	Code string `json:"code"`
	Language string `json:"language"`
	TimeoutMs *float64 `json:"timeout_ms,omitempty"`
}

// SearchFilesInput contains the input parameters for the search_files tool.
// Search file contents by plain text pattern. Returns matching file metadata (path, name, size). Suppo
type SearchFilesInput struct {
	CaseSensitive *bool `json:"case_sensitive,omitempty"`
	ContextLines *float64 `json:"context_lines,omitempty"`
	Path *string `json:"path,omitempty"`
	Pattern string `json:"pattern"`
	Regex *bool `json:"regex,omitempty"`
}

// ShareWithPublicInput contains the input parameters for the share_with_public tool.
// Share a file via an unlisted public link (experimental). Requires enabling at /keys. Shared links ne
type ShareWithPublicInput struct {
	Action string `json:"action"`
	Path *string `json:"path,omitempty"`
}

// UploadSessionInput contains the input parameters for the upload_session tool.
// Manage staged binary uploads for large files. Use action 'start' to begin, 'append' to send chunks, 
type UploadSessionInput struct {
	Action string `json:"action"`
	Content *string `json:"content,omitempty"`
	ExpectedBytes *int `json:"expected_bytes,omitempty"`
	MimeType *string `json:"mime_type,omitempty"`
	Mode *string `json:"mode,omitempty"`
	PartNumber *int `json:"part_number,omitempty"`
	Path *string `json:"path,omitempty"`
	UploadID *string `json:"upload_id,omitempty"`
}

// VaultSecretInput contains the input parameters for the vault_secret tool.
// Securely store, retrieve, list, rotate, and delete workspace secrets. Encrypted at rest, never in fi
type VaultSecretInput struct {
	Action string `json:"action"`
	AllowedAgentIDs *[]string `json:"allowedAgentIds,omitempty"`
	Description *string `json:"description,omitempty"`
	Encoding *string `json:"encoding,omitempty"`
	ExpiresAt *string `json:"expiresAt,omitempty"`
	Mode *string `json:"mode,omitempty"`
	Name *string `json:"name,omitempty"`
	Purpose *string `json:"purpose,omitempty"`
	Reveal *bool `json:"reveal,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	Value *string `json:"value,omitempty"`
}

// WebhookInput contains the input parameters for the webhook tool.
// Manage webhook endpoints for real-time event notifications. Register HTTPS URLs to receive HMAC-SHA2
type WebhookInput struct {
	Action string `json:"action"`
	Active *bool `json:"active,omitempty"`
	Description *string `json:"description,omitempty"`
	Events *[]string `json:"events,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	URL *string `json:"url,omitempty"`
	WebhookID *string `json:"webhook_id,omitempty"`
}

// WorkspaceCheckpointInput contains the input parameters for the workspace_checkpoint tool.
// Manage workspace snapshots and templates. For snapshots: create, list, restore, and delete named che
type WorkspaceCheckpointInput struct {
	Action string `json:"action"`
	CheckpointID *string `json:"checkpoint_id,omitempty"`
	Description *string `json:"description,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	Name *string `json:"name,omitempty"`
	Template *string `json:"template,omitempty"`
}

// WorkspaceCollaborateInput contains the input parameters for the workspace_collaborate tool.
// Multi-agent coordination: claim/release file locks, leave handoff notes, discover active agents. Loc
type WorkspaceCollaborateInput struct {
	Action string `json:"action"`
	IncludeRead *bool `json:"include_read,omitempty"`
	Limit *float64 `json:"limit,omitempty"`
	Message *string `json:"message,omitempty"`
	Path *string `json:"path,omitempty"`
	ToAgent *string `json:"to_agent,omitempty"`
	TTLSeconds *float64 `json:"ttl_seconds,omitempty"`
}

// WriteFileInput contains the input parameters for the write_file tool.
// Write UTF-8 text or base64-encoded binary to a file. Creates an immutable version automatically.
type WriteFileInput struct {
	Content string `json:"content"`
	Encoding *string `json:"encoding,omitempty"`
	IfVersion *float64 `json:"if_version,omitempty"`
	Path string `json:"path"`
}

